---
title: "p9380_hw2"
author: "Ashley Tseng"
date: "1/30/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(maps)
library(maptools)
library(data.table)
library(RColorBrewer)
library(classInt)
library(rgdal)
library(sf)
library(ggplot2)
library(ggsn)
```


```{r hw2}
setwd("/Users/ashleytseng/OneDrive - cumc.columbia.edu/MPH/Spring 2020/EHSC P9380_Advanced GIS/Labs/Lab 2/p9380_lab2")

nj_cty = map('county', 'new jersey', fill = TRUE, col = palette())

list.names.nj = strsplit(nj_cty$names,",")

map.IDs = as.character(tolower(sapply(list.names.nj, function(x) x[2])))
head(map.IDs, n = 21)
map.IDs = gsub("cape may", "capemay", map.IDs)
head(map.IDs, n = 21)

nj_cty_sp = map2SpatialPolygons(nj_cty, IDs = map.IDs, proj4string = CRS("+init=epsg:3424"))
head(map.IDs, n = 21)

rwj = fread("rwj_rank.csv", stringsAsFactors = F, data.table = F, colClasses = list(character = c("FIPS")))

nj_rwj = subset(rwj, State == "New Jersey")
head(nj_rwj, n = 21)

nj_rwj$County = gsub("Cape May", "capemay", nj_rwj$County)
head(nj_rwj$County, n = 21)
row.names(nj_rwj) = as.character(tolower(nj_rwj$County))

head(row.names(nj_rwj), n = 21)
head(map.IDs, n = 21)

nj_rwj_df = SpatialPolygonsDataFrame(nj_cty_sp,nj_rwj)
summary(nj_rwj_df)

summary(nj_rwj_df$HB.Rank)
nj_rwj_df$HB.Rank = as.numeric(nj_rwj_df$HB.Rank)
summary(nj_rwj_df$HB.Rank)
nj_rwj_df$HB.Rank = 21 - nj_rwj_df$HB.Rank


writeOGR(nj_rwj_df, 
         dsn = "working_directory", 
         layer = "RWJ_NJ", 
         driver = "ESRI Shapefile")


rwj_sf_nj = st_read(dsn = "working_directory",
                  layer = "RWJ_NJ")

coords = st_coordinates(rwj_sf_nj)

nj_map = ggplot(data = rwj_sf_nj) +
  geom_sf() +
  aes(fill = cut_number(as.numeric(as.character(HB_Rank)), 5)) +
  scale_fill_brewer(name = "Quantile", palette = "Purples", 
                    labels = c("1st",
                             "2nd",
                             "3rd",
                             "4th",
                             "5th")) +
  labs(title = "County-Level Health Behaviors Ranking, New Jersey",
       subtitle = "By Ashley Tseng\n",
       caption = "\nData source: Robert Wood Johnson Foundation") +
  theme(axis.text = element_text(size = 6),                       
        axis.title = element_text(size = 6),
        plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        plot.caption = element_text(),
        legend.position = "right") +
  north(rwj_sf_nj, scale = 0.15, symbol = 1, location = "bottomleft")
  
nj_map

```


